# The environment for the Docker image
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - numba
  - lxml
  - loguru
  - click
  - pandas
  - pyteomics
  - pip
  - wheel
  - git
  - spectrum_utils
  - pyarrow
  - polars
  - psims
  - hdf5plugin>=3.10.0

  # system tools:
  - procps-ng
  - gcc
  - gxx_impl_linux-64
  - gxx_linux-64
  - binutils_impl_linux-64
  - binutils
