# The environment for the Docker image
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - numba
  - lxml
  - loguru
  - click
  - pandas
  - pyteomics
  - wheel
  - git
  - pyarrow
  - polars
  - psims
  - hdf5plugin>=3.10.0
  - rdkit
  - appdirs
  - lark
  - pip:
      - spectrum_utils>=0.4.2 # problems with fastobo dependency

  # system tools:
  - procps-ng
  - gcc
  - gxx_impl_linux-64
  - gxx_linux-64
  - binutils_impl_linux-64
  - binutils
