# The environment for the Docker image
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - numba
  - lxml
  - loguru
  - click
  - pyteomics
  - pip
  - wheel
  - procps-ng
  - git
